import React from 'react'
import {motion,useScroll,useTransform} from "framer-motion"
const Box1 = () => {
  const {scrollYProgress}=  useScroll()
  const lw=useTransform(scrollYProgress,[0,1],["0%","100%"])
  return (
    <div className='min-h-screen w-full pt-20 bg-violet-700 text-white font-mono font-extrabold text-xl letter-wide'>
        <motion.span className='bg-yellow-500 p-2 fixed top-0 left-0 '
        style={{
            width:lw,
            transition:"width 0.1s ease"
        }}
        ></motion.span>

        <p className='p-6'>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti veniam, cupiditate harum eaque officia, voluptatum nesciunt aut architecto sapiente perferendis esse porro corporis corrupti. Voluptatem expedita quae veniam ipsam id!
            Repellendus, beatae! Officia est dolorum optio libero repudiandae cum perferendis quo alias, ad eveniet quod! Inventore, eaque. Exercitationem perferendis, assumenda, delectus facilis autem provident, quam velit nesciunt labore nihil laboriosam?
            Praesentium quibusdam omnis perspiciatis alias sint at tempore ut illo, sapiente modi, necessitatibus voluptas enim mollitia. Dicta quasi quae eius minima suscipit. Error est exercitationem tenetur optio ipsam facere nostrum!
            Non vero, explicabo minus facilis voluptate laboriosam nisi consequatur quos eveniet tempora eaque commodi nostrum iste a provident accusamus quam dicta illum quibusdam amet eius debitis et harum dolor. Velit.
            Iusto asperiores repellendus vitae, obcaecati quod hic ducimus odit. Molestias necessitatibus voluptatum quia quo nihil cupiditate sequi voluptatibus pariatur tempore tenetur? Culpa sunt neque at labore. Dolor ea earum deleniti!
            Quo, cumque magni? Vel beatae perspiciatis pariatur qui nisi fugit modi, expedita quisquam veniam nulla tempore officiis. Sunt debitis corporis iste? Suscipit unde, necessitatibus molestias tempore deserunt illo id itaque.
            Quia quaerat blanditiis repellendus, in eos ut voluptas eveniet asperiores nulla exercitationem, ullam similique sit, ipsum veritatis aperiam? Consectetur minus in ratione sed cupiditate natus nihil sit, dignissimos quia nam.
            Incidunt, hic unde repellat, nulla cum voluptas animi possimus ipsa sunt deserunt quasi maxime quo. Suscipit doloremque sed, unde eum et officia? Non totam modi accusantium, magnam minima aliquam possimus.
            Dolore tenetur eligendi architecto deleniti, ex ipsam deserunt at fugiat dolorum maxime nesciunt omnis debitis obcaecati quia minus beatae id error saepe. Quisquam, vitae qui quaerat harum nisi dignissimos id.
            Adipisci dolore sunt pariatur temporibus nemo quos similique ratione officia recusandae iste soluta reprehenderit eaque ipsa, qui perferendis odio cumque! Quo architecto dolor sunt repellat ipsam tenetur. Ad, vitae expedita?
            Vitae corrupti iusto commodi voluptatibus reiciendis quidem animi provident cupiditate in fuga tempora officiis, ducimus, ex officia repudiandae nemo illo harum consequuntur alias excepturi itaque, sit cumque similique dolorum! Voluptate?
            Sunt laboriosam minus illo temporibus nulla magnam voluptate dolores nisi aut consequatur. Quas dignissimos odit, eum est id corporis hic, optio perferendis saepe aut quasi laudantium accusamus ullam rerum inventore?
            Natus consectetur ipsum quae eos temporibus laboriosam repellendus voluptatibus sunt alias inventore illo, vero molestiae! Accusantium eius temporibus expedita aut sequi nobis qui at. Inventore perferendis minus deserunt nesciunt ea.
            Quia, harum facere corporis velit adipisci nemo. Laboriosam maiores obcaecati autem eos, numquam cum, praesentium non rerum atque cupiditate velit eligendi, illo qui aliquam necessitatibus! Voluptatum magni veniam amet repudiandae!
            Odio eos, officiis numquam dolor laboriosam praesentium similique ipsa magnam quaerat qui minima aspernatur voluptas voluptatibus voluptatum aut molestias expedita dolore obcaecati vel adipisci at eligendi amet ratione veritatis! Esse.
            Deserunt consectetur perferendis, eum mollitia quas sit! Aliquid dolores distinctio ipsam voluptate cum atque labore, temporibus dolorem nam laborum dolore laudantium tempore quae expedita, reiciendis quos voluptas eaque totam alias!
            Rerum nesciunt, dolorem assumenda est reprehenderit alias vero? Iure deserunt consequuntur, ratione non at earum error libero voluptate. Veritatis quia a ullam possimus accusamus aperiam quo voluptas et itaque doloribus?
            Sequi quod reprehenderit voluptatem sint sunt, nemo magni quas ut impedit quos nostrum ipsa odio perferendis error aliquam earum at mollitia voluptatibus enim quidem ab quibusdam, aspernatur quaerat veniam? In.
            Dignissimos, est! Molestiae inventore odio blanditiis quas ipsa nemo? Laudantium nobis veniam ratione earum. Repellat atque nam beatae obcaecati. Velit labore earum porro eius commodi tenetur provident nihil, illo odio.
            Suscipit dicta velit iste quas quisquam tempora asperiores aliquam exercitationem obcaecati libero molestiae animi, dolor atque blanditiis sit quidem cupiditate nemo, nihil ullam voluptate laborum id corporis adipisci eum? Placeat?
            Nostrum, ratione veniam. Ipsa consectetur expedita natus autem incidunt eaque voluptatum nihil esse! Mollitia facere eveniet pariatur quod modi repellendus! Deleniti rem consectetur est nisi esse. Repellendus officiis deleniti error?
            Ipsam, quasi! At, itaque? Hic quod dolorum, nulla omnis soluta eligendi quaerat blanditiis. Tenetur voluptatum saepe minima repellendus pariatur laudantium quibusdam sit, sapiente, eum culpa reprehenderit possimus fuga magni dolorum.
            Laboriosam repellendus, quas quo ad asperiores non, nam dignissimos odit possimus expedita quidem! Iure, odio libero ratione labore, perspiciatis eos eum quasi excepturi alias quibusdam veritatis accusantium autem porro rerum!
            Consequuntur natus, ad consequatur odio dignissimos sit ipsam officiis sunt saepe cum, accusantium fugit laboriosam nesciunt! Atque distinctio ex minima unde ab explicabo illo? Labore cumque fugit maiores illum necessitatibus?
            Suscipit voluptatum amet, aliquam tempore velit obcaecati molestias aspernatur nihil omnis quidem! Unde, quis. Vitae dolores vel exercitationem, praesentium ipsum sint delectus distinctio, illum enim possimus deserunt voluptas molestias explicabo.
            Magnam consequuntur libero consectetur cumque maxime nisi dolore odio placeat optio asperiores quidem quia accusamus hic sit quos reiciendis possimus sed impedit rerum dignissimos, dolores ut accusantium facilis. Qui, fuga.
            Quisquam animi alias, numquam placeat vel consequuntur debitis iusto reprehenderit perferendis et iure quibusdam temporibus dolores nesciunt, molestias tempore obcaecati, id asperiores. Fuga, modi minus dolore nesciunt ipsa omnis quod?
            Maiores illo quas cum asperiores modi obcaecati possimus sed quod dignissimos accusantium, exercitationem nulla? Enim expedita ratione obcaecati aperiam eligendi officiis dolores labore animi accusantium? Amet necessitatibus ab laudantium dicta.
            Molestiae ipsa cum minima libero placeat commodi praesentium quod repudiandae hic quam optio maxime vitae accusantium possimus vel nihil magnam iusto quidem officia repellendus sed, assumenda quos ab! Inventore, nesciunt.
            Atque corporis dolorem accusamus voluptate, laboriosam iusto animi minus ipsum vel iste voluptatem, quis at ipsam alias enim quaerat fugiat quod saepe eos! Dolorem officiis culpa nobis! Ad, alias earum?
            Corrupti nam perspiciatis itaque ipsa dolorum consequatur. Consectetur amet repellat modi labore rem quibusdam nesciunt quasi unde quos sed delectus asperiores doloremque quisquam numquam voluptate, id nam, minima nulla magni!
            Totam fugit tempore ex fuga eum, quam omnis corporis sunt? Deserunt consectetur ex perspiciatis aspernatur reiciendis consequuntur exercitationem minus suscipit voluptates totam quo veritatis quibusdam tempora quos, doloribus fugiat repellendus.
            Quia voluptatum et ratione fugit molestiae molestias veritatis mollitia, exercitationem enim esse ut aliquid rerum iure quaerat eaque maxime nobis, doloremque eius corporis, error facere sunt. Suscipit a rerum maxime.
            Ex, quia! Nesciunt architecto placeat quod excepturi aut dolor impedit sint et nulla corrupti similique voluptate sequi, id rem eveniet tempore blanditiis accusamus sapiente quos quaerat voluptates natus. Aut, impedit.
            Commodi architecto aspernatur repellendus excepturi vero officiis perferendis vel, non quo nisi, molestias provident similique neque adipisci voluptas, ab autem magni totam nesciunt debitis fuga quos? Asperiores veniam ut non!
            In laboriosam quis repellendus tempore unde voluptatem quae vero ipsa eos, tempora officia? Aliquid ea mollitia sequi fugiat itaque voluptatum, veniam, eveniet officia quo esse saepe autem totam atque rem!
            Libero eum voluptatem doloremque, fugiat totam rem enim quod deleniti officiis. Voluptas sunt quisquam sed numquam iste! Aliquid magni possimus nobis cupiditate temporibus sed, asperiores assumenda, vel maiores dicta vero!
            Quaerat optio incidunt molestiae, tenetur ipsa quae ut recusandae. Odio soluta facere minus alias numquam accusamus cum distinctio vel quisquam. Vitae ducimus nobis praesentium temporibus eos totam quibusdam, commodi sequi.
            Sequi placeat omnis quasi? Quia odit cupiditate assumenda molestiae nostrum, illo rerum dolores nobis, voluptatem excepturi maxime quas magnam accusamus minima sunt expedita? Quo atque alias eius nobis ipsa ab?
            Maiores, laboriosam quidem dolorum voluptate ducimus nostrum tempore, consectetur asperiores velit minima nesciunt odit officiis voluptates architecto quasi nobis temporibus? Distinctio, possimus. Omnis voluptatibus, molestias sit veniam suscipit rerum quidem.
            Dolorum iusto, a eius amet maiores corporis voluptatum repellendus magnam tempore, omnis nostrum vitae nisi ullam consectetur temporibus natus, doloremque eveniet nulla labore velit nam quos error. Magnam, necessitatibus harum!
            Autem, voluptatibus quos. Vel, placeat esse porro officiis aspernatur repellat nostrum quo odio aut officia nisi maxime dolor eum aliquid ipsum distinctio sit quam id voluptatibus iure magnam dignissimos soluta.
            Sed velit aliquid voluptatem, voluptatibus illo, quae minus a excepturi perspiciatis maiores, iste accusantium tempore ipsam modi in consequuntur. Magni harum illo distinctio facere qui amet repudiandae, cupiditate quisquam voluptates.
            Voluptas, iure earum beatae corrupti ipsum officia repudiandae soluta illo facilis expedita laborum ab veniam dolorum nihil dolore quae aspernatur est. Asperiores, consequatur harum! Autem dignissimos dolorem facilis eaque. Beatae.
            Voluptatum ipsa distinctio aliquam sint minima accusantium unde ex porro! Repellendus libero ducimus maiores est dolorem quaerat harum aliquam, id architecto commodi nobis inventore ab veniam autem aperiam expedita exercitationem.
            Nihil suscipit natus doloremque nemo sequi quos laudantium mollitia voluptatibus, eaque eum vitae odit nobis iusto doloribus culpa sapiente deserunt eveniet totam commodi delectus, quam cumque magni? Praesentium, quaerat error.
            Ullam dolorum aliquam tempora officiis quos ad ex minus sint, aperiam nisi nulla laudantium sapiente repudiandae, sunt a. Magnam explicabo voluptatem, ab voluptatum voluptate minima doloribus porro! Beatae, facere modi?
            Officia consequatur provident earum beatae nesciunt, iusto dicta quos reprehenderit sapiente necessitatibus explicabo ex aperiam quaerat fugit nobis consequuntur aliquid suscipit dolor delectus recusandae deserunt. Dolorem autem consequuntur praesentium culpa?
            Consequatur incidunt, obcaecati commodi vero eaque, ipsam harum quia ducimus doloremque, et consequuntur! Officia, minus ab voluptatum, velit a sequi recusandae, nam illo laborum consequuntur voluptates nemo unde! Fugit, iusto!
            Cum qui ut optio id accusamus, aspernatur aliquam facilis non quos odio sapiente iste et, architecto deleniti quia maxime in repudiandae autem aperiam exercitationem impedit? At alias doloribus accusantium eveniet!
            Nesciunt laudantium nisi magni similique distinctio minima eius iure, quam corrupti hic a minus deleniti rerum dolorem porro modi voluptatem ullam incidunt obcaecati eos? Iusto voluptatibus excepturi accusantium hic nobis.
            Nulla ad, architecto, ipsam laudantium, numquam molestias fuga id praesentium eligendi exercitationem quidem? Totam maiores consequatur modi repudiandae aspernatur? Blanditiis officia ipsum incidunt eum numquam delectus at in. Ullam, ut.
            Mollitia necessitatibus quos odio qui iure non laborum quam doloribus ducimus nostrum. Recusandae, expedita praesentium eum consequuntur voluptates laborum, autem, explicabo quas assumenda soluta repellendus quis perferendis odit? Quibusdam, qui?
            Culpa dolore, ex recusandae eveniet deserunt explicabo quia cupiditate vel sunt fugit delectus tempora non, expedita libero. Perspiciatis ex nobis facere illum? Odit nesciunt quae error, laborum debitis voluptas vitae!
            Iure earum repellat fugit? Delectus ex, alias obcaecati deserunt fugit nostrum sed reiciendis vel error. Nostrum cumque debitis blanditiis vitae, aspernatur minus non quibusdam commodi nobis voluptates dolorem ab vero!
            Magni accusamus amet alias quaerat nisi! Quos eveniet cumque optio modi unde expedita ullam tempore aliquam ab quas explicabo, ea animi, odit neque amet iste mollitia deserunt at recusandae ratione?
            Cumque, placeat repellendus, asperiores consequuntur neque natus ullam aspernatur, voluptatem minus ipsum facilis eius aliquid error soluta vel eos quis cum illum accusantium earum! Amet omnis quo inventore nostrum aliquam.
            Sunt voluptates perspiciatis itaque doloribus? Quos corporis quis in quibusdam officiis atque, nobis aut porro ipsam, vero fugit. Dolorum quas, a ullam modi omnis aliquid. Doloremque maxime earum voluptates distinctio?
            Illo ullam inventore quis voluptatem, dolorem facere consequatur ut voluptatum excepturi in molestiae laudantium, ipsum tempora autem quasi numquam debitis, minima sequi blanditiis adipisci error vel corporis? Vitae, maxime voluptates.
            Magni sapiente perferendis illum iusto consectetur sed soluta consequuntur! Nostrum qui nisi quas error voluptate ex magni cum quo odio corporis dicta, officia soluta fuga voluptatum consequuntur, quis molestias repellendus?
            Velit incidunt unde ratione repellendus dolorem expedita recusandae, totam magni, natus nemo modi aliquam itaque laboriosam impedit aliquid sint eligendi similique perspiciatis ea facilis! Voluptatem debitis quidem tempora minima qui!
            Repellendus reprehenderit minima asperiores nisi excepturi distinctio molestias obcaecati, fuga aspernatur, laboriosam pariatur facilis voluptatibus beatae accusamus est aut, error qui ipsa. Vitae repellendus tempore magnam similique voluptatum veritatis voluptates?
            Perferendis quo laborum provident beatae maxime placeat, possimus doloribus ullam rerum adipisci inventore culpa quam laboriosam nihil quod id quibusdam tempore cum consequuntur, voluptatem sequi atque fugit tenetur. Blanditiis, tempora.
            Voluptate dolore, numquam voluptas mollitia magni autem veritatis sint tempora minus cumque explicabo veniam asperiores id, commodi temporibus nisi fugit, nemo debitis modi. Nobis beatae distinctio ullam voluptatem, amet maxime.
            Cum alias porro a nihil temporibus sed sint laboriosam, doloribus ut enim perspiciatis autem nemo vitae explicabo optio veniam, quae cumque dolorem nam est perferendis non unde? Amet, enim nemo?
            Labore distinctio cum delectus non alias aperiam eos reprehenderit expedita architecto est id, facere eaque excepturi tenetur facilis. Sed natus quae odit numquam distinctio voluptatum autem eligendi suscipit qui porro?
            Deserunt, nihil possimus, ad voluptate non nemo aliquam nam, inventore quaerat porro atque. Doloremque quo eius delectus facere voluptates. Quasi necessitatibus voluptate ipsa sit! Cumque nam eligendi labore distinctio iure?
            Officia suscipit laudantium libero omnis dicta placeat, temporibus repudiandae culpa reiciendis, sint minima quas cum inventore harum earum saepe! Est assumenda dolorum fugiat ullam maiores nam veritatis tenetur, excepturi cumque.
            Voluptatem voluptate consectetur temporibus, quibusdam excepturi vero? Nobis magni, laboriosam non necessitatibus dolor quaerat eveniet amet sed corporis excepturi voluptates, cupiditate similique natus, cum voluptatibus maxime? Sequi officia aliquid aspernatur.
            Deleniti unde inventore fugit. Odio deleniti saepe obcaecati omnis placeat dolor quasi reprehenderit facilis recusandae tempora. Quia enim, vel impedit iure saepe assumenda odit veniam atque expedita necessitatibus similique ab!
            Consectetur eligendi quidem laudantium doloribus quo nam quibusdam incidunt voluptas quae ut quam eos velit ipsum enim dignissimos harum facere praesentium ipsa molestias, adipisci reprehenderit dolorum cupiditate! Consectetur, repudiandae sed!
            Suscipit id voluptatum sapiente repellendus corrupti odio fugit? Ipsam inventore debitis numquam laborum illum earum labore quis alias officiis a quae, impedit itaque, fugiat, aut mollitia consequatur. Vel, quasi quos.
            Quam repellat voluptatum autem, iure reprehenderit voluptate doloremque quos dolores dignissimos quas nihil, est nemo obcaecati molestias veritatis sit iste sunt velit temporibus necessitatibus cum excepturi, optio doloribus! Aliquid, illo?
            Voluptates, ad dicta aut laudantium quasi mollitia ducimus id quae nam ex molestias necessitatibus sint veniam ea qui sit animi alias quam autem aliquam. Quibusdam molestiae aliquam culpa quod eos?
            Laborum repellat nisi ipsum voluptate corrupti quas ab earum dolore quam, doloremque eum non molestias minus ad facere quis magni, aspernatur a? Neque quae omnis libero sapiente quidem a quo.
            Rerum, mollitia sequi nobis temporibus porro expedita at blanditiis atque! Minima sunt quam eligendi aspernatur sit praesentium dolor sed vel, asperiores, adipisci rerum hic fugit nesciunt. Harum ipsum consequuntur architecto?
            Animi excepturi quia explicabo quod. Quaerat animi aliquam labore minima corporis dolorum vel, suscipit excepturi illo tenetur inventore odit error dolor. Quaerat quod totam officia tempore labore, saepe ut nulla?
            Exercitationem eos mollitia recusandae sit, quidem numquam non nemo molestiae corporis quam. Accusantium, minima obcaecati dolorum exercitationem illum incidunt tempore minus temporibus distinctio amet. Asperiores eaque harum quam rem facilis!
            Quaerat magni mollitia odit nobis iusto voluptatem ea quae ratione, quisquam aliquam dolores maxime officia, deleniti, velit voluptatibus pariatur sed facilis cupiditate saepe culpa nisi fugiat labore illo dolor? Asperiores.
            Expedita ex sit, dolor laborum est asperiores rerum illo repellat beatae neque cupiditate eius suscipit cumque fugit. Vitae numquam, necessitatibus esse aspernatur animi amet hic explicabo impedit iste excepturi provident.
            Asperiores aspernatur veritatis natus, dicta necessitatibus voluptas, alias voluptatum reprehenderit nulla voluptatibus velit fugit. Obcaecati aliquam pariatur optio autem error quibusdam magni odit, nihil nobis, laboriosam, dignissimos aut perspiciatis sequi.
            Neque ullam, illum mollitia nulla et obcaecati quod magni cum fugiat consequuntur sed nemo animi quidem dicta aspernatur earum voluptates pariatur qui quo libero corporis dignissimos asperiores quae. Obcaecati, vel?
            Atque quibusdam tempore nobis culpa corrupti quasi, repellat perferendis. Voluptatem quam excepturi architecto, tenetur sequi doloribus perferendis nesciunt quae eveniet placeat. Temporibus totam error repudiandae harum quod, placeat accusantium ipsum.
            Aliquam modi officia tenetur voluptate ab dolorem sapiente dolorum error distinctio iure sed incidunt eveniet perspiciatis, dignissimos dolor nihil obcaecati suscipit, ipsam voluptatum nostrum consequatur et! Facilis temporibus illum consequuntur.
            Sapiente rem quibusdam suscipit atque itaque, voluptas illum sunt assumenda quae ipsam officiis facilis, soluta obcaecati neque aliquam dicta, temporibus nesciunt deserunt labore harum. Quae porro nemo quis nesciunt maxime.
            Quidem illum atque deleniti earum sapiente ea harum numquam placeat facilis voluptatibus? Rerum voluptates quasi ea atque vitae ad illo in! Nam ipsa dicta quam ipsam laudantium officia praesentium dignissimos!
            Repudiandae explicabo sed, necessitatibus qui ex cumque voluptas id non quo accusantium illum vero deleniti quod doloremque. Maiores ipsa commodi animi suscipit quae labore vel, laborum aperiam officia ratione et.
            Magni quo sed id aspernatur dolor delectus maxime, tenetur molestiae vero laboriosam reiciendis adipisci eligendi sequi esse quaerat mollitia error amet, velit non nemo ut a eos accusamus! Provident, perferendis.
            Sit pariatur aliquam ut temporibus recusandae cumque exercitationem tempore animi architecto dolore! Molestiae, debitis eligendi a error aliquid alias aut ut architecto ratione aperiam modi. Ea aut enim odit aperiam?
            Quo suscipit animi dolor eaque odio placeat vel nesciunt, earum modi iusto molestiae officia, ex doloribus sint asperiores quia distinctio. Dolore iste excepturi placeat nihil cumque, ducimus fugit dolor. Saepe?
            Distinctio sequi repellendus aliquid! Esse est omnis et voluptatibus sed. Deserunt soluta praesentium sunt illum consectetur eum odit error voluptatum? Vitae voluptates cum facilis perspiciatis dicta provident nulla corporis laborum!
            Maiores porro velit nostrum ducimus, fuga eaque dignissimos exercitationem cumque odio nobis obcaecati quas omnis mollitia molestias consequatur fugit perferendis a quos quia placeat maxime? Atque, eum? Commodi, qui totam!
            Praesentium ea porro ipsum eum vitae non, libero, reprehenderit minima quas, ad voluptas aspernatur earum deleniti natus sapiente consequatur odio consequuntur est accusantium repellendus neque voluptate atque quisquam. Et, ullam!
            Vitae at, tempore rem illum, harum laudantium quae velit repellendus atque eligendi, possimus itaque qui alias ad earum exercitationem blanditiis sint suscipit? Eligendi, beatae tempore explicabo at illo laborum aperiam?
            Doloremque minima distinctio doloribus perferendis facilis sed odit optio dolores saepe, harum ea dolorum mollitia quidem, veritatis excepturi numquam enim provident. Itaque culpa quasi, fugiat velit repellat omnis asperiores pariatur?
            Consequatur dignissimos totam tenetur architecto corporis maxime similique suscipit rem corrupti reiciendis, sit obcaecati commodi exercitationem ducimus molestias quas quos perferendis ullam optio voluptates id. Voluptates possimus repudiandae provident dolor.
            Quas possimus ipsa quis quia voluptate incidunt natus tempore! Ut incidunt laboriosam saepe natus, quae et, pariatur voluptas dolorem fugit beatae atque! Quae dolore repellat cumque earum fugiat, debitis eligendi?
            Suscipit sed ab molestiae blanditiis. Itaque error sequi quae quam aliquam dicta, qui debitis. Eum, excepturi? Autem dolor quaerat eius? Et quidem corrupti voluptatem tenetur. Eaque laudantium quas voluptas. Minima?
            Consequatur enim alias recusandae consequuntur a qui omnis voluptate deserunt illo eveniet veniam repudiandae architecto doloribus impedit nesciunt aspernatur, hic fugiat, tempora ducimus accusantium, laboriosam eos aliquid animi. Expedita, quas.
            Pariatur assumenda, impedit esse fugiat magni iste, voluptatibus laboriosam ex odio sequi cupiditate nemo saepe eligendi possimus accusamus obcaecati fugit facilis porro et. Quaerat sint earum error, molestias esse facere!
        </p>
    </div>
  )
}

export default Box1